# Generated by Django 4.2.5 on 2023-10-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_education_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='default_profile_picture.png', upload_to='profile_picture'),
        ),
    ]
